#!/usr/bin/env bash
# .cursor/scripts/install.sh
# Idempotent Cloud Agent bootstrap for Revy: system deps (PostgreSQL 16 + pgvector,
# Redis 7), Python deps (pipenv), Node deps, local .env files, DB role/db/extensions,
# and Alembic migrations. Safe to re-run. Runtime services are (re)started in start.sh.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
export PATH="$HOME/.local/bin:$PATH"
export DEBIAN_FRONTEND=noninteractive

PG_MAJOR=16
DB_ROLE="revy_app"
DB_PASSWORD="revy_local_pw"

echo "==> [install] system packages (PostgreSQL ${PG_MAJOR} + pgvector, Redis)"
if ! command -v psql >/dev/null 2>&1 || ! command -v redis-server >/dev/null 2>&1; then
  sudo apt-get update -qq
  sudo apt-get install -y -qq \
    postgresql postgresql-contrib "postgresql-${PG_MAJOR}-pgvector" redis-server
fi

echo "==> [install] pipenv"
if ! command -v pipenv >/dev/null 2>&1; then
  pip install --user --quiet pipenv
fi

echo "==> [install] start PostgreSQL cluster (for DB provisioning)"
sudo pg_ctlcluster "${PG_MAJOR}" main start 2>/dev/null || true
for _ in $(seq 1 20); do
  sudo -u postgres psql -tAc "SELECT 1" >/dev/null 2>&1 && break
  sleep 1
done

echo "==> [install] role, databases, extensions"
sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${DB_ROLE}') THEN
    CREATE ROLE ${DB_ROLE} LOGIN PASSWORD '${DB_PASSWORD}' SUPERUSER;
  END IF;
END \$\$;
SQL
for db in revy revy_test; do
  sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='${db}'" | grep -q 1 \
    || sudo -u postgres createdb -O "${DB_ROLE}" "${db}"
  sudo -u postgres psql -d "${db}" -v ON_ERROR_STOP=1 -f "${REPO_ROOT}/deploy/sql/postgres-extensions.sql" >/dev/null
done

echo "==> [install] backend/.env"
if [ ! -f "${REPO_ROOT}/backend/.env" ]; then
  cat > "${REPO_ROOT}/backend/.env" <<'ENV'
# backend/.env — Cloud Agent local development (generated by .cursor/scripts/install.sh)
ENVIRONMENT=development
DEBUG=true
LOG_LEVEL=DEBUG
LOG_FORMAT=console
SECRET_KEY=local-dev-only-change-me
ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173

DATABASE_URL=postgresql+asyncpg://revy_app:revy_local_pw@localhost:5432/revy
TEST_DATABASE_URL=postgresql+asyncpg://revy_app:revy_local_pw@localhost:5432/revy_test

REDIS_URL=redis://localhost:6379/0
CELERY_BROKER_URL=redis://localhost:6379/0
CELERY_RESULT_BACKEND=redis://localhost:6379/1

KEYCLOAK_URL=http://localhost:8080
KEYCLOAK_REALM=revy
KEYCLOAK_CLIENT_ID=revy-api
KEYCLOAK_CLIENT_SECRET=local-revy-api-secret
KEYCLOAK_FRONTEND_CLIENT_ID=revy-web

REGISTRATION_REQUIRE_ADMIN_APPROVAL=false
REGISTRATION_REQUIRE_PROFILE_FORM=false

EMAIL_PROVIDER=console
APP_PUBLIC_URL=http://localhost:5173

GITHUB_APP_ID=
GITHUB_APP_PRIVATE_KEY_PATH=/path/to/github-app.pem
GITHUB_WEBHOOK_SECRET=local-webhook-secret
REVY_BOT_LOGIN=revy[bot]

REVY_EMBEDDING_BACKEND=voyage
VOYAGE_API_KEY=
REVY_EMBEDDING_MODEL=voyage-code-3
REVY_EMBEDDING_DIMENSIONS=1024

REVY_REVIEWER_PROVIDER=moonshot
REVY_LLM_PROVIDER=moonshot
REVY_MOONSHOT_MODEL_STANDARD=kimi-k2.7-code
REVY_MOONSHOT_MODEL_DEEP=kimi-k3
REVY_MOONSHOT_MODEL_CRITICAL=kimi-k3
MOONSHOT_API_KEY=
REVY_JUDGE_PROVIDER=anthropic
ANTHROPIC_API_KEY=
REVY_ANTHROPIC_MODEL=claude-sonnet-5

REVY_REPOS_ROOT=/tmp/revy/repos
REVY_WORKTREES_ROOT=/tmp/revy/worktrees

STRIPE_ENABLED=false

REVY_DEFAULT_REVIEW_PROFILE=standard
REVY_REVISION_TIMEOUT_STANDARD_SECONDS=900
REVY_REVISION_TIMEOUT_DEEP_SECONDS=1500
REVY_REVISION_TIMEOUT_CRITICAL_SECONDS=1800
PIPELINE_RETENTION_DAYS=90

SENTRY_DSN=
SENTRY_ENABLE_IN_TEST=false

PIPENV_VENV_IN_PROJECT=1
ENV
fi

echo "==> [install] frontend/.env.local"
if [ ! -f "${REPO_ROOT}/frontend/.env.local" ]; then
  cp "${REPO_ROOT}/frontend/.env.example" "${REPO_ROOT}/frontend/.env.local"
fi

echo "==> [install] runtime scratch dirs"
mkdir -p /tmp/revy/repos /tmp/revy/worktrees /tmp/revy/exports

echo "==> [install] backend Python deps"
cd "${REPO_ROOT}/backend"
pipenv install
pipenv run install

echo "==> [install] Alembic migrations"
pipenv run alembic upgrade head

echo "==> [install] frontend Node deps"
cd "${REPO_ROOT}/frontend"
npm ci --no-audit --no-fund

echo "==> [install] stop PostgreSQL (clean state for snapshot; start.sh restarts it)"
sudo pg_ctlcluster "${PG_MAJOR}" main stop 2>/dev/null || true

echo "==> [install] done"
